export enum Routes {
  Chat = "Chat",
  ChatDrawer = "ChatDrawer",
  ChatboxList = "ChatboxList",
  MainScreen = "MainScreen",
  Inbox = "Inbox",
  Profile = "Profile",
  UserProfile = "UserProfile",
  UserList = "UserList",
  Rating = "Rating",
  Login = "Login",
  SignUp = "Sign up",
  AuthButtonList = "Auth Button List",
  Interests = "Interests",
  CreateGroup = "Create Group",
  ForgetPassword = "Forget Password",
  ResetPassword = "Reset Password",
  Onboarding = "Onboarding",
  OnboardingInitial = "Onboarding initial",
  OnboardingTerms = "Onboarding Terms & Conditions",
  OnboardingInterest = "Onboarding add interests",
  OnboardingTermsContent = "Onboarding Terms & Conditions Content",
  Calling = "Calling",
}
