export const DEFAULT_DEBOUNCE_TIME = 300
export const DEFAULT_HIT_SLOP = { top: 15, left: 15, bottom: 15, right: 15 }
export const MESSAGE_LIMIT = 30
export const PARTNER_LIMIT = 10
export const PARTICIPANT_LIMIT = 10
export const NOTIFICATION_TIMEOUT = 5000
export const ONBOARD_USER_INTERESTS = 7
export const MENTION_EVERYONE_ID = "everyone"
export const CALLER_FOR_JOIN = "unknown"
export const UNREAD_MAX_PAGES_THRESHOLD = 5
export const LONG_PRESS_DURATION = 250
